name: Lint
on:
    workflow_dispatch:
    pull_request:
        branches: [ main ]
jobs:
    phpcs:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            -   name: Checkout Code
                uses: actions/checkout@v4

            # Setup PHP on the runner.
            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    extensions: mbstring,xml
                    tools: composer,cs2pr

            # Validate the composer.json file.
            # @link https://getcomposer.org/doc/03-cli.md#validate
            -   name: Validate Composer installation
                run: composer validate --no-check-all

            # Install dependencies and handle caching in one go.
            # @link https://github.com/marketplace/actions/install-composer-dependencies
            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v2
                with:
                    # Bust the cache at least once a month - output format: YYYY-MM-DD.
                    custom-cache-suffix: $(date -u -d "-0 month -$(($(date +%d)-1)) days" "+%F")

            # Check the codestyle of the files.
            # The results of the CS check will be shown inline in the PR via the CS2PR tool.
            # @link https://github.com/staabm/annotate-pull-request-from-checkstyle/
            -   name: Check PHP code style
                id: phpcs
                run: composer lint -- --report-full --report-checkstyle=./phpcs-report.xml

            -   name: Show PHPCS results in PR
                if: ${{ always() && steps.phpcs.outcome == 'failure' }}
                run: cs2pr ./phpcs-report.xml
