name: Release

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

jobs:
    version-check:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            -   name: Checkout Code
                uses: actions/checkout@v3

            # Install dependencies (if Makefile is used)
            -   name: Set Up Environment
                run: sudo apt-get update && sudo apt-get install -y make

            # Extract and compare versions
            -   name: Check Version Bump
                id: version-check
                run: |
                    # Extract the version from the plugin file using the Makefile command
                    CURRENT_VERSION=$(make version)
                    echo "Current Version: $CURRENT_VERSION"

                    # Extract the tag version from the GitHub tag (strip the 'v' prefix)
                    TAG_VERSION=${GITHUB_REF##*/} # Extract the tag name (e.g., 'refs/tags/v1.2.3' -> 'v1.2.3')
                    TAG_VERSION=${TAG_VERSION#v} # Remove 'v' prefix (e.g., 'v1.2.3' -> '1.2.3')
                    echo "Git Tag Version: $TAG_VERSION"

                    # Compare the two versions
                    if [ "$CURRENT_VERSION" != "$TAG_VERSION" ]; then
                      echo "❌Error: The current version ($CURRENT_VERSION) does not match the Git tag version ($TAG_VERSION)."
                      exit 1
                    fi

    # Deploy & Release
    deploy:
        runs-on: ubuntu-latest
        needs: version-check
        steps:
            # Checkout the repository
            -   name: Checkout Code
                uses: actions/checkout@v3

            # Deploy action to generate the ZIP file
            -   name: Generate Plugin ZIP
                uses: 10up/action-wordpress-plugin-deploy@v2
                with:
                    slug: mondu-trade-account
                    dry-run: true
                    generate-zip: true
                env:
                    SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                    SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

            # Create a release
            - name: Create GitHub release
              uses: softprops/action-gh-release@v1
              with:
                  files: ${{github.workspace}}/${{ github.event.repository.name }}.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
