name: Release
on:
    push:
        tags:
            - '*'
    workflow_dispatch:
jobs:
    version-check:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository.
            -   name: Checkout Code
                uses: actions/checkout@v4

            # Install dependencies (if Makefile is used).
            -   name: Set Up Environment
                run: sudo apt-get update && sudo apt-get install -y make

            # Extract and compare versions.
            -   name: Check Version Bump
                id: version-check
                run: |
                    # Extract the version from the plugin file using the Makefile command
                    CURRENT_VERSION=$(make version)
                    echo "Current Version: $CURRENT_VERSION"

                    # Extract the tag version from the GitHub tag
                    TAG_VERSION=${GITHUB_REF##*/} # Extract the tag name (e.g., 'refs/tags/1.2.3' -> '1.2.3')
                    echo "Git Tag Version: $TAG_VERSION"

                    # Compare the two versions
                    if [ "$CURRENT_VERSION" != "$TAG_VERSION" ]; then
                      echo "❌Error: The current version ($CURRENT_VERSION) does not match the Git tag version ($TAG_VERSION)."
                      exit 1
                    fi

    # Deploy & Release
    deploy:
        runs-on: ubuntu-latest
        needs: version-check
        steps:
            # Checkout the repository.
            -   name: Checkout Code
                uses: actions/checkout@v4

            # Setup PHP on the runner.
            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    tools: wp-cli

            # Install WP Deps.
            -   name: Install Dependencies
                run: wp package install wp-cli/dist-archive-command:@stable --allow-root

            # Generates the ZIP file using the WP CLI
            -   name: Generate ZIP file
                run: |
                    wp dist-archive ./ "$(pwd)/mondu-trade-account.zip" --allow-root
                    ls -la $(pwd) # Verify ZIP file location

            # Deploy action to generate the ZIP file
            #            -   name: Generate Plugin
            #                uses: 10up/action-wordpress-plugin-deploy@stable
            #                with:
            #                    dry-run: true
            #                    generate-zip: true
            #                env:
            #                    SLUG: mondu-trade-account
            #                    SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
            #                    SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

            # Create a release.
            -   name: Create GitHub Release
                uses: softprops/action-gh-release@v1
                with:
                    files: mondu-trade-account.zip
                    draft: true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
