name: Security

on:
    push:
    pull_request:
    workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name.
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    security:
        name: 'Security check'
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            # This action checks the `composer.lock` file against known security vulnerabilities in the dependencies.
            # https://github.com/marketplace/actions/the-php-security-checker
            -   name: Run Security Check
                uses: symfonycorp/security-checker-action@v4
